Repository swoyam2609/CodeChef-Solution, pull requests merged in 2022-10, with the labels that each got.

#13 Missing CODE OF CONDUCT resolved.
  CODE_OF_CONDUCT.md
Labels: documentation, good first issue, hacktoberfest-accepted

#27 START54 and README file added
  JULY221D/README.md
  START54/CREDS.cpp
  START54/DPRTMNTSEASY.cpp
  START54/EQDIS.cpp
  START54/KFLIP.cpp
  START54/SUBARRAYGAME.cpp
  START54/TCKTFINE.cpp
  START54/TEAMOF2.cpp
Labels: good first issue, hacktober22, hacktoberfest-accepted

#28 Added all solutions for issue no: #11
  LTIME111/MAXPREFFLIP.cpp
  LTIME111/MEXPERMDIF.cpp
  LTIME111/MEXSUBTR.cpp
  LTIME111/SORTARRAY.cpp
  LTIME111/SUB12OP.cpp
  LTIME111/TreeColoring.cpp
Labels: hacktober22, hacktoberfest-accepted

#29 Added all the solutions for CodeChef September Long
  SEP221/DIV-4/Bob_at_the_Bank.cpp
  SEP221/DIV-4/Chef_and_Wire_Frames.cpp
  SEP221/DIV-4/Good_Pairs.cpp
  SEP221/DIV-4/Interesting_Subarray.cpp
  SEP221/DIV-4/Pokemon_Battles.cpp
  SEP221/DIV-4/Speed_Limit_Test.cpp
Labels: hacktober22, hacktoberfest-accepted

#30 Added .gitignore file and 3 Solutions for OCT long Challenge
  .gitignore
  JULY221D/AUCTION.exe
  OCT221/DIV4/BUILDINGRACE.cpp
  OCT221/DIV4/MINPIZZA.cpp
  OCT221/DIV4/PODIUM.cpp
  OCT221/README.md
Labels: hacktober22, hacktober-accepted, hacktoberfest-accepted

#32 Added Solution for last question of div4
  START59/DIV4/AlternativeSuffering.cpp
Labels: enhancement, hacktober22, hacktoberfest-accepted

#36 Uploaded all codes of Starters 55
  START55/BALLBOX.cpp
  START55/BALLSEQ.cpp
  START55/BROKENPHONE.cpp
  START55/FEVER.cpp
  START55/MEANMEDIAN.cpp
  START55/NZXOR.cpp
  START55/ORTUPLES.cpp
  START55/PERMCLEAR.cpp
Labels: good first issue, hacktober22, hacktoberfest-accepted

#37 Added 4 codes of STARTERS 60 Division 4
  START60/DIV4/CUTPAPER.cpp
  START60/DIV4/EXPERT.cpp
  START60/DIV4/REMOVECARDS.cpp
  START60/DIV4/TAXES.cpp
  START60/README.md
Labels: good first issue, hacktober22, hacktoberfest-accepted

#40 Added START46
  START46/ArmyTraining.cpp
  START46/ArraySorting.cpp
  START46/CountingWords.cpp
  START46/GroupAssignment.cpp
  START46/MATH1Enrolment.cpp
  START46/PrimeXor.cpp
  START46/SortTheStrign.cpp
  START46/VowelAnxiety.cpp
Labels: good first issue, hacktober22, hacktoberfest-accepted

#43 Codes of Starters49 uploaded
  START49/goodindices.cpp
  START49/highfrequency.cpp
  START49/isithotorcold.cpp
  START49/maximisethetastiness.cpp
  START49/monks.cpp
  START49/nbuttom1bulb.cpp
  START49/splitthestring.cpp
  START49/validminimum.cpp
Labels: good first issue, hacktober22, hacktoberfest-accepted

#47 Added codes for START51
  AUG221/AandBequal.cpp
  AUG221/HELLOEQN.cpp
  AUG221/MAXSUBS.cpp
  AUG221/SALESEASON.cpp
  AUG221/TWOTRAINS.cpp
  START39/chessrating.c
  START51/DiffMedians.cpp
  START51/Dominantelement.cpp
  START51/Finalpopulation.cpp
  START51/SplitN.cpp
  START51/TVdiscount.cpp
Labels: enhancement, good first issue, hacktober22, hacktoberfest-accepted

#44 Solution added for ARRPAL START60/DIV4
  START60/DIV4/PALINDROMEFLIPPING.cpp
  START60/DIV4/YETANOTHERPALINDROME.cpp
Labels: good first issue, hacktober22, hacktoberfest-accepted

#51 START47 added
  START47/ChefOnDate.cpp
  START47/ChessTime.cpp
  START47/ConstructN.cpp
  START47/EndSorted.cpp
  START47/MinimumCoins.cpp
Labels: good first issue, hacktober22, hacktoberfest-accepted

#53 STARTER-55
  STARTER-55/BALLBOX.cpp
  STARTER-55/BROKENPHONE.cpp
  STARTER-55/MEANMEDIAN.cpp
  STARTER-55/ORTUPLES.cpp
  STARTER-55/PERMCLEAR.cpp
Labels: good first issue, hacktober22, hacktoberfest-accepted

#57 Added solutions for DIV 3 in Starters 44
  START44/DIV 3/Alternating Strings.cpp
  START44/DIV 3/Atleast and Atmost.cpp
  START44/DIV 3/Dense Bracket Sequence.cpp
  START44/DIV 3/Jogging.cpp
  START44/DIV 3/Palindromes Not Allowed.cpp
  START44/DIV 3/The Attack of Knight.cpp
  START44/DIV 3/Triple Xor.cpp
  START44/DIV 4/q1.cpp
Labels: good first issue, hacktober22, hacktober-accepted, hacktoberfest-accepted

#63 Create 'EQUALISE' of AUG221D
  'EQUALISE' of AUG221D
Labels: enhancement, hacktober22, hacktoberfest-accepted

#65 Codechef Starter48 |Div 4| solution
  START48/.cph/.Buy_Lamps.cpp_08cdb306d63f4f56ad9745146b10f42b.prob
  START48/.cph/.Fill_Candies.cpp_20eaa0d8292812776aaf70bb8a504a3e.prob
  START48/.cph/.Fill_The_Grid.cpp_c549b5f8ce2786266f61acd7dea33c32.prob
  START48/.cph/.Make_Palindrome_2.cpp_e4dfde6849d7e1cdc9eb692be4cca7b9.prob
  START48/Buy_Lamps.cpp
  START48/Fill_Candies.cpp
  START48/Fill_The_Grid.cpp
  START48/Make_Palindrome_2.cpp
  START48/Passes_for_Fair.cpp
Labels: good first issue, hacktober22, hacktoberfest-accepted

#61 Create PassesForFair.cpp
  START48/PassesForFair.cpp
Labels: hacktober22, hacktoberfest-accepted

#64 Added 2 codes of Starter 61 division 4
  START61/DIV4/MINIMISE LCS.cpp
  START61/DIV4/SUBARRAY REMOVAL.cpp
Labels: enhancement, hacktober22, hacktoberfest-accepted

#67 Codechef56
  START56/CHEFLAND GAMES.cpp
  START56/FAR AWAY.cpp
  START56/K-SUBARRAYS.cpp
  START56/MAXIMISE COLOURS.cpp
  START56/NEAREST EXIT.cpp
Labels: good first issue, hacktober22, hacktoberfest-accepted

#70 START42
  START42/Age_limit.cpp
  START42/Construct_an_array.cpp
  START42/Divisible_by_3.cpp
  START42/Equal_distribution.cpp
  START42/How_many_maximums.cpp
  START42/Maximise_set_bits.cpp
  START42/Minimum_number_of_flips.cpp
  START42/Minimum_or_maximum.cpp
  START42/Readme.md
  START42/Sorting_array.cpp
Labels: hacktober22, hacktoberfest-accepted

#73 age_limit.cpp
  START42/equal_distribution.cpp
  age_limit.cpp
Labels: enhancement, hacktober22, hacktoberfest-accepted

#76 Added 4 codes of STARTERS62 DIV4
  STARTERS62/DIV4/CHEFSCORE.cpp
  STARTERS62/DIV4/MAKEMULTIPLE.cpp
  STARTERS62/DIV4/MAXDIFFMIN.cpp
  STARTERS62/DIV4/README.md
  STARTERS62/DIV4/XJUMP.cpp
Labels: good first issue, hacktober22, hacktoberfest-accepted
